* added detection of the conflict between -fPIC and -pg.      It correctly detects that it works on my machine, but it'll have to be tested on a machine where it shouldn't work to ensure it detects that as well.

diff --git a/centrallix/configure b/centrallix/configure
--- a/centrallix/configure
+++ b/centrallix/configure
@@ -4324,6 +4324,62 @@ rm -f confcache
 
 
 
+    echo "$as_me:$LINENO: checking if -fPIC and -pg can be used at the same time" >&5
+echo $ECHO_N "checking if -fPIC and -pg can be used at the same time... $ECHO_C" >&6
+    temp="$CFLAGS"
+    CFLAGS="-fPIC -pg -Werror"
+        cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  PROFILE="-pg"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+PROFILE=""
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+    if test "$PROFILE" = "-pg"; then
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    fi
+    CFLAGS="$temp"
+
+
+
+
+
+
 	echo "$as_me:$LINENO: checking if gzip support is desired" >&5
 echo $ECHO_N "checking if gzip support is desired... $ECHO_C" >&6
 
@@ -5895,6 +5951,7 @@ echo "${ECHO_T}no" >&6
 
 
 
+
 if test "$WITH_DYNAMIC_LOAD" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
@@ -6494,6 +6551,7 @@ s,@OBJDRIVERMODULES@,$OBJDRIVERMODULES,;t t
 s,@OBJDRIVERS@,$OBJDRIVERS,;t t
 s,@STATIC_CFLAGS@,$STATIC_CFLAGS,;t t
 s,@STATIC_LIBS@,$STATIC_LIBS,;t t
+s,@PROFILE@,$PROFILE,;t t
 CEOF
 
 _ACEOF
