* added gzip osdriver

diff --git a/centrallix/configure b/centrallix/configure
--- a/centrallix/configure
+++ b/centrallix/configure
@@ -827,6 +827,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dynamic-load  disable dynamic loading
+  --disable-gzip          disable gzip support
   --disable-http          disable HTTP support
   --enable-mime           enable MIME support
   --enable-dbl            enable DBL support
@@ -846,6 +847,9 @@ Optional Packages:
   --with-centrallix-os=FILE
                           Full path of centrallix OS directory (default is
                           /var/centrallix/os)
+  --with-zlib=PATH        library path for zlib library (default is /usr/lib)
+  --with-zlib-inc=PATH    include path for zlib headers (default is
+                          /usr/include)
   --with-sybase-inc=PATH  include path for Sybase headers (default is
                           /opt/sybase/include)
   --with-sybase-lib=PATH  library path for Sybase libraries (default is
@@ -4268,6 +4272,263 @@ rm -f confcache
 
 
 
+	echo "$as_me:$LINENO: checking if gzip support is desired" >&5
+echo $ECHO_N "checking if gzip support is desired... $ECHO_C" >&6
+
+	# Check whether --enable-gzip or --disable-gzip was given.
+if test "${enable_gzip+set}" = set; then
+  enableval="$enable_gzip"
+  WITH_GZIP="$enableval"
+else
+  WITH_GZIP="yes"
+
+fi;
+
+	if test "$WITH_GZIP" = "no"; then
+	    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	else
+	    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+# Check whether --with-zlib or --without-zlib was given.
+if test "${with_zlib+set}" = set; then
+  withval="$with_zlib"
+  zlib_libdir="$withval"
+else
+  zlib_libdir="/usr/lib"
+fi;
+
+
+# Check whether --with-zlib-inc or --without-zlib-inc was given.
+if test "${with_zlib_inc+set}" = set; then
+  withval="$with_zlib_inc"
+  zlib_incdir="-I$withval"
+else
+  zlib_incdir="/usr/include"
+
+fi;
+
+	    temp=$CPPFLAGS
+	    CPPFLAGS="$CPPFLAGS $zlib_incdir"
+	    tempC=$CFLAGS
+	    CFLAGS="$CFLAGS $zlib_incdir"
+	    if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for zlib.h" >&5
+echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6
+if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
+echo "${ECHO_T}$ac_cv_header_zlib_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking zlib.h usability" >&5
+echo $ECHO_N "checking zlib.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <zlib.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking zlib.h presence" >&5
+echo $ECHO_N "checking zlib.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <zlib.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: zlib.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: zlib.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: zlib.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: zlib.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: zlib.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: zlib.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: zlib.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for zlib.h" >&5
+echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6
+if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_zlib_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
+echo "${ECHO_T}$ac_cv_header_zlib_h" >&6
+
+fi
+if test $ac_cv_header_zlib_h = yes; then
+  WITH_GZIP="yes"
+else
+  WITH_GZIP="no"
+
+fi
+
+
+	    CPPFLAGS="$temp"
+	    CFLAGS="$tempC"
+
+	    if test "$WITH_GZIP" = "yes"; then
+		GZIP_CFLAGS="-I$zlib_incdir"
+		temp=$LIBS
+		LIBS="$LIBS -L$zlib_libdir -lz"
+		echo "$as_me:$LINENO: checking for gzread in -lz" >&5
+echo $ECHO_N "checking for gzread in -lz... $ECHO_C" >&6
+if test "${ac_cv_lib_z_gzread+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz -lz $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char gzread ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+gzread ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_z_gzread=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_z_gzread=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_z_gzread" >&5
+echo "${ECHO_T}$ac_cv_lib_z_gzread" >&6
+if test $ac_cv_lib_z_gzread = yes; then
+  WITH_GZIP_ZLIB="yes"
+else
+  WITH_GZIP_ZLIB="no"
+fi
+
+		if test "$WITH_GZIP_ZLIB" = "no"; then
+		    WITH_GZIP="no"
+		else
+		    GZIP_LIBS="-L$zlib_libdir $zlib_lib"
+		fi
+		LIBS="$temp"
+	    fi
+	fi
+
+	echo "$as_me:$LINENO: checking if GZIP support can be enabled" >&5
+echo $ECHO_N "checking if GZIP support can be enabled... $ECHO_C" >&6
+	if test "$WITH_GZIP" = "yes"; then
+	    cat >>confdefs.h <<\_ACEOF
+#define USE_GZIP 1
+_ACEOF
+
+	    if test "$WITH_DYNAMIC_LOAD" = "yes"; then
+		OBJDRIVERMODULES="$OBJDRIVERMODULES objdrv_gzip.so"
+	    else
+		STATIC_CFLAGS="$STATIC_CFLAGS $GZIP_CFLAGS"
+		STATIC_LIBS="$STATIC_LIBS $GZIP_LIBS"
+		OBJDRIVERS="$OBJDRIVERS objdrv_gzip.o"
+	    fi
+	    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	else
+	    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	fi
+
+
+
+
+
+
+
+
+
 	echo "$as_me:$LINENO: checking if HTTP support is desired" >&5
 echo $ECHO_N "checking if HTTP support is desired... $ECHO_C" >&6
 
@@ -6098,6 +6359,8 @@ s,@CPP@,$CPP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@CXLIBDIR@,$CXLIBDIR,;t t
 s,@CXOSDIR@,$CXOSDIR,;t t
+s,@GZIP_CFLAGS@,$GZIP_CFLAGS,;t t
+s,@GZIP_LIBS@,$GZIP_LIBS,;t t
 s,@SYBASE_LIBS@,$SYBASE_LIBS,;t t
 s,@SYBASE_CFLAGS@,$SYBASE_CFLAGS,;t t
 s,@xmlconfig@,$xmlconfig,;t t
