Configure updates to work on Fedora Core 1 (nasty interface change in glibc __ctype_b)

diff --git a/centrallix/configure b/centrallix/configure
--- a/centrallix/configure
+++ b/centrallix/configure
@@ -4729,6 +4729,65 @@ rm -f confcache
 
 
 
+	has_ctype_b="test"
+	echo "$as_me:$LINENO: checking if __ctype_b is present and usable" >&5
+echo $ECHO_N "checking if __ctype_b is present and usable... $ECHO_C" >&6
+	temp="$CFLAGS"
+	CFLAGS=""
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ctype.h>
+int
+main ()
+{
+int main() { int x = *(__ctype_b+'a'); return x; }
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  has_ctype_b="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+has_ctype_b=""
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+	if test "$has_ctype_b" = "yes"; then
+	    cat >>confdefs.h <<\_ACEOF
+#define HAVE_CTYPE_B 1
+_ACEOF
+
+	    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	else
+	    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	fi
+
+
+
+
+
+
 	echo "$as_me:$LINENO: checking if -fPIC and -pg can be used at the same time" >&5
 echo $ECHO_N "checking if -fPIC and -pg can be used at the same time... $ECHO_C" >&6
 	temp="$CFLAGS"
@@ -5395,11 +5454,13 @@ fi
 
 	    CPPFLAGS="$temp"
 
+
 	    if test "$WITH_SYBASE" = "yes"; then
-		SYBASE_CFLAGS="-I$sybase_incdir"
-		temp=$LIBS
-		LIBS="$LIBS -L$sybase_libdir"
-		echo "$as_me:$LINENO: checking for ct_connect in -lct" >&5
+				if test "$has_ctype_b" = "yes"; then
+		    SYBASE_CFLAGS="-I$sybase_incdir"
+		    temp=$LIBS
+		    LIBS="$LIBS -L$sybase_libdir"
+		    echo "$as_me:$LINENO: checking for ct_connect in -lct" >&5
 echo $ECHO_N "checking for ct_connect in -lct... $ECHO_C" >&6
 if test "${ac_cv_lib_ct_ct_connect+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -5459,6 +5520,36 @@ else
   WITH_SYBASE_CT="no"
 fi
 
+		else
+		    SYBASE_CFLAGS="-I$sybase_incdir"
+		    temp=$LIBS
+		    LIBS="$LIBS -L$sybase_libdir"
+		    libfile="$sybase_libdir/libct.so"
+		    as_ac_File=`echo "ac_cv_file_$libfile" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $libfile" >&5
+echo $ECHO_N "checking for $libfile... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$libfile"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  WITH_SYBASE_CT="yes"
+else
+  WITH_SYBASE_CT="no"
+fi
+
+		fi
 		if test "$WITH_SYBASE_CT" = "no"; then
 		    WITH_SYBASE="no"
 		else
