* added a check for -export-dynamic as a flag to ld -- it isn't supported on Mac OS X

diff --git a/centrallix/configure b/centrallix/configure
--- a/centrallix/configure
+++ b/centrallix/configure
@@ -2297,6 +2297,56 @@ rm -f confcache
 
 
 
+    echo "$as_me:$LINENO: checking if -export-dynamic can be given to ld" >&5
+echo $ECHO_N "checking if -export-dynamic can be given to ld... $ECHO_C" >&6
+    temp="$CFLAGS"
+    CFLAGS="-Wl,-export-dynamic"
+    if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+int main(){return 0;}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  EXPORT_DYNAMIC="-export-dynamic"
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+EXPORT_DYNAMIC=""
+
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+    if test "$EXPORT_DYNAMIC" = "-export-dynamic"; then
+	EXPORT_DYNAMIC=",$EXPORT_DYNAMIC"
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    fi
+    CFLAGS="$temp"
+
+
+
+
+
 echo "$as_me:$LINENO: checking for main in -lcrypt" >&5
 echo $ECHO_N "checking for main in -lcrypt... $ECHO_C" >&6
 if test "${ac_cv_lib_crypt_main+set}" = set; then
@@ -5772,6 +5822,7 @@ echo "${ECHO_T}no" >&6
 
 
 
+
 if test "$WITH_DYNAMIC_LOAD" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
@@ -6355,6 +6406,7 @@ s,@SED@,$SED,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
+s,@EXPORT_DYNAMIC@,$EXPORT_DYNAMIC,;t t
 s,@CPP@,$CPP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@CXLIBDIR@,$CXLIBDIR,;t t
