- changed configuration to allow different levels of hardening (mainly, so   asserts can be enabled without enabling the ds checksum stuff). - initial working version of the smmalloc (shared memory malloc) module. - test suite for smmalloc "make test". - results from test suite run on 1.4GHz Athlon, GCC 2.96, RH73 - smmalloc not actually tested between two processes yet. - TO-FIX: smmalloc interprocess locking needs to be reworked to prefer   spinlocks where doable instead of using sysv semaphores which are SLOW.

diff --git a/centrallix-lib/configure b/centrallix-lib/configure
--- a/centrallix-lib/configure
+++ b/centrallix-lib/configure
@@ -824,12 +824,17 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-mtask-debug    enable mTask debugging support
-  --enable-hardening      enable support for application-level security
-                          hardening; large performance hit
   --enable-optimization   turn on build optimization; incompatible with the
-                          --enable-hardening option
+                          --with-hardening=high option
   --disable-shared-libCentrallix
                           disable building a shared libCentrallix
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-hardening        enable support for application-level security
+                          hardening. Can have a large performance hit. Values:
+                          none, low, medium, high; default: none
 
 Some influential environment variables:
   CC          C compiler command
@@ -3437,7 +3442,7 @@ fi
 done
 
 
-CXLIBVER="0.7.4"
+CXLIBVER="0.7.4a"
 FINAL_TARGETS="libCentrallix.a libStParse.a"
 
 
@@ -3570,26 +3575,55 @@ _ACEOF
 
 	echo "$as_me:$LINENO: checking if application-level hardening desired" >&5
 echo $ECHO_N "checking if application-level hardening desired... $ECHO_C" >&6
-	# Check whether --enable-hardening or --disable-hardening was given.
-if test "${enable_hardening+set}" = set; then
-  enableval="$enable_hardening"
-  WITH_HARDENING="$enableval"
+
+# Check whether --with-hardening or --without-hardening was given.
+if test "${with_hardening+set}" = set; then
+  withval="$with_hardening"
+  WITH_HARDENING="$withval"
 else
-  WITH_HARDENING="no"
+  WITH_HARDENING="none"
 
 fi;
-	if test "$WITH_HARDENING" = "no"; then
-	    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-	else
-	    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-	    DEFS="$DEFS -DCXLIB_SECH"
+	if test "$WITH_HARDENING" = "none"; then
+	    echo "$as_me:$LINENO: result: none" >&5
+echo "${ECHO_T}none" >&6
+	    CFLAGS="$CFLAGS -DNDEBUG"
+	elif test "$WITH_HARDENING" = "low"; then
+	    echo "$as_me:$LINENO: result: low: magic number checking" >&5
+echo "${ECHO_T}low: magic number checking" >&6
+	    CFLAGS="$CFLAGS -DNDEBUG -DDBMAGIC"
+
+cat >>confdefs.h <<\_ACEOF
+#define USING_DBMAGIC 1
+_ACEOF
+
+	elif test "$WITH_HARDENING" = "medium"; then
+	    echo "$as_me:$LINENO: result: medium: magic number checking and assertions" >&5
+echo "${ECHO_T}medium: magic number checking and assertions" >&6
+	    CFLAGS="$CFLAGS -DDBMAGIC"
+
+cat >>confdefs.h <<\_ACEOF
+#define USING_DBMAGIC 1
+_ACEOF
+
+	elif test "$WITH_HARDENING" = "high"; then
+	    echo "$as_me:$LINENO: result: high: magic number checking, assertions, and data structure verification" >&5
+echo "${ECHO_T}high: magic number checking, assertions, and data structure verification" >&6
+	    CFLAGS="$CFLAGS -DDBMAGIC -DCXLIB_SECH"
+
+cat >>confdefs.h <<\_ACEOF
+#define USING_DBMAGIC 1
+_ACEOF
+
 
 cat >>confdefs.h <<\_ACEOF
 #define CXLIB_SECURITY_HARDENING 1
 _ACEOF
 
+	else
+	    { { echo "$as_me:$LINENO: error: invalid setting for --with-hardening; values=none,low,medium,high" >&5
+echo "$as_me: error: invalid setting for --with-hardening; values=none,low,medium,high" >&2;}
+   { (exit 1); exit 1; }; }
 	fi
 
 
@@ -3608,14 +3642,8 @@ fi;
     if test "$WITH_OPTIMIZATION" = "no"; then
 	echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-	DEFS="$DEFS -DDBMAGIC"
-
-cat >>confdefs.h <<\_ACEOF
-#define USING_DBMAGIC 1
-_ACEOF
-
     else
-	if test "$WITH_HARDENING" = "yes"; then
+	if test "$WITH_HARDENING" = "high"; then
 	    { { echo "$as_me:$LINENO: error: Optimization and security hardening are mutually exclusive; please at most specify one or the other but not both" >&5
 echo "$as_me: error: Optimization and security hardening are mutually exclusive; please at most specify one or the other but not both" >&2;}
    { (exit 1); exit 1; }; }
