Fix make valtest.

diff --git a/centrallix-lib/Makefile.in b/centrallix-lib/Makefile.in
--- a/centrallix-lib/Makefile.in
+++ b/centrallix-lib/Makefile.in
@@ -6,7 +6,7 @@
 ## This library is made available under the GNU Lesser General Public
 ## License, version 2.1.
 ##
-## Copyright (C) 1998-2001 LightSys Technology Services, Inc.
+## Copyright (C) 1998-2026 LightSys Technology Services, Inc.
 ##
 
 @SET_MAKE@
@@ -75,6 +75,13 @@ INCLUDEFILES:=$(patsubst include/cxlibconfig-all.h,,$(INCLUDEFILES))
 
 TESTFILES:=$(wildcard tests/test_$(TONLY)*.c)
 TESTPROGS:=$(patsubst %.c,%.bin,$(TESTFILES))
+
+## Valgrind setup for "make valtest".  Override VALGRINDFLAGS to change the
+## checks performed, and set VALGRINDLOG to a directory to get one valgrind
+## log per test instead of the errors being printed with the test results.
+VALGRIND?=valgrind
+VALGRINDFLAGS?=-q
+VALGRINDLOG?=
 
 .SUFFIXES:	.c .o .lo
 
@@ -175,9 +182,20 @@ valtest:	$(TESTPROGS)
 	@printf "Running Regression Tests Under Valgrind...\n"
 	@printf "%-62.62s  %s\n" "Test Name" "Stat Ops/sec"
 	@printf "%-62.62s  %s\n" "----------------------------------------------------------------" "--------------"
+	@if [ "$(VALGRINDLOG)" != "" ]; then mkdir -p "$(VALGRINDLOG)"; fi
 	@for PROG in $$( ls $(TESTPROGS) ); do \
 	    if [ "$$TONLY" = "" -o "$${PROG#tests/test_$$TONLY}" != "$$PROG" ]; then \
-		valgrind -q $$PROG; \
+		NAME=$${PROG##*/}; \
+		NAME=$${NAME%.bin}; \
+		if [ "$(VALGRINDLOG)" = "" ]; then \
+		    $(VALGRIND) $(VALGRINDFLAGS) $$PROG; \
+		else \
+		    LOG="$(VALGRINDLOG)/$$NAME.log"; \
+		    $(VALGRIND) $(VALGRINDFLAGS) --error-exitcode=125 --log-file="$$LOG" $$PROG; \
+		    if [ "$$?" = "125" ]; then \
+			printf "  valgrind: errors reported -- %s\n" "$$LOG"; \
+		    fi; \
+		fi; \
 	    fi \
 	done 
 
